# === Training Hyperparameters ===
batch_size: 8
lr: 0.0003
epochs: 10
train_test_split: 0.9
weight_decay: 0.001

# === Evaluation and Logging ===
eval_frequency: 1     # Evaluate every N epochs
log_frequency: 10     # Log every N batches

# === Runtime Environment ===
device: cuda          # Set to 'cuda' or 'cpu'
random_seed: 42

# === Generate ===
ckpt_path: 'train_exp/run_epoch10_lr0.0003_bs8_time20250625-204048/epoch_10.pt'
input_image_path: 'data/images/000000046872.jpg'
max_generate: 128
decoder_temperature: 1.0
top_k: 50