# === Training Hyperparameters ===
batch_size: 16
lr: 0.0005
epochs: 100
train_test_split: 0.9
weight_decay: 0.001

# === Evaluation and Logging ===
eval_frequency: 1
log_frequency: 1

# === Runtime Environment ===
device: cuda          # Set to 'cuda' or 'cpu'
random_seed: 42

# === Generate ===
ckpt_path: 'train_exp/run_epoch50_lr0.0005_bs8_time20250628-134926/epoch_50.pt'