# === Training Hyperparameters ===
batch_size: 16
lr: 0.0002
epochs: 30
warmup_epochs: 5
max_retr_lambda: 0.5
min_retr_lambda: 0.1
train_split: 0.7
val_split: 0.2
weight_decay: 0.0001

# === Evaluation and Logging ===
eval_frequency: 1
log_frequency: 1

# === Runtime Environment ===
device: cuda
random_seed: 42

# === Generate ===
ckpt_path: 'train_exp/run_epoch50_lr0.0002_bs16_20250706-074952/epoch_15.pt'