# === Training Hyperparameters ===
batch_size: 16
lr: 0.0005
epochs: 20
max_retr_lambda: 0.5
train_test_split: 0.9
weight_decay: 0.001

# === Evaluation and Logging ===
eval_frequency: 1
log_frequency: 1

# === Runtime Environment ===
device: cuda          # Set to 'cuda' or 'cpu'
random_seed: 42

# === Generate ===
ckpt_path: ''